### ISSUE TITLE
Hexadecimal numbers are converted as strings

### ISSUE THREAD

**Issue by jotego** [komkom/toml#3]
TOML specifies that numbers starting by 0x are hexadecimal, but this package deals with them as strings. For example:

```
[hextest]
hexvalue=0x10
decvalue=16
```

gets rendered in JSON as
```
{
   "hextest": {
      "hexvalue": "0x10",
      "decvalue": 16
   }
}
```
I think it should be 
```
{
   "hextest": {
      "hexvalue": 16,
      "decvalue": 16
   }
}
```

**Comment by komkom** [comment]
Thanks for the comment. Its a good point. There are several types in toml which can only be represented as strings in JSON but in this case it makes more sense to convert into a number I guess. 
I will try to change this as soon as I have some time.

**Comment by komkom** [comment]
What do you think about the following change?
https://github.com/komkom/toml/pull/4

**Comment by jotego** [comment]
It looks perfect. It will convert octal and binary too. Thank you!
